// OrigoKeysErrorCodes.h
// Copyright (c) 2018 HID Origo Mobile Services
//
// All rights reserved.

/**
 * The domain used for all NSError objects originating from Origo Keys.
 */
extern NSErrorDomain OrigoKeysErrorDomain;
/**
 * The domain used for all NSError objects originating from Origo Keys while communicating with TSM.
 */
extern NSErrorDomain OrigoKeysHttpErrorDomain;

/**
 *
 * NSError objects generated by OrigoKeys will contain one of these codes.
 * Please look at the individual codes to see what they mean. The codes ending
 * in RetryError indicates that a retry can be attempted.
 *
 * @note since version 2.0
 */
typedef NS_ENUM(NSInteger, OrigoKeysErrorCode) {
    /**
     * 99, An internal error occured. Recommended user action is to restart app or reboot device
     */
    OrigoKeysErrorCodeInternal = 99,
    /**
     * 999, A fatal error occured. The keys have been lost and the user needs to setup again
     */
    OrigoKeysErrorCodeCorruptedStorage = 999,
    /**
     * 107 Attempt to invoke a method which requires an endpoint that is setup. Recommended user action is to contact the key administrator and request an invitation code.
     */
    OrigoKeysErrorCodeEndpointNotSetup = 107,
    /**
     * 401, One asynchrounous method of the API is already running. Recommended user action is to retry the action.
     */
    OrigoKeysErrorCodeSDKBusy = 401,
    /**
     * 700, The TSM replied NOT ELIGIBLE (FATAL during Setup, Invitation code is consumed and can no longer be used). Recommended user action is to contact the key administrator.
     */
    OrigoKeysErrorCodeDeviceNotEligible = 700,
    /**
     * 701, Server replied API INCOMPATIBLE. Recommended user action is to upgrade the application. Recommended developer is to upgrade the SDK.
     */
    OrigoKeysErrorCodeSDKIncompatible = 701,
    /**
     * 702, The server communication failed. This is normally because of a network problem. Recommended user action is to check internet connectivity or try again later.
     */
    OrigoKeysErrorCodeServerUnreachable = 702,
    /**
     * 703, The TSM failed to install the endpoint with a fatal error (FATAL, Invitation code no longer useful). Recommended user action is to contact the key administrator.
     */
    OrigoKeysErrorCodeDeviceSetupFailed = 703,
    /**
     * 901 The TSM Reported that the invitation code was not valid. Recommended user action is to retype or contact the key administrator.
     */
    OrigoKeysErrorCodeInvalidInvitationCode = 901,
    /**
     * 1101   OrigoKeysManager was unable to serve the request to open the specified reader since the request contained
     *        an OpeningType that was not in the list of permitted OpeningTypes. Recommended user/developer action is to reconfigure reader.
     */
    OrigoKeysErrorCodeOpeningTypeNotPermitted = 1101,
    /**
     * 1103  OrigoKeysManager were unable to serve the request since Bluetooth Low Energy is unavailable. Recommended user action is to change permissions.
     */
    OrigoKeysErrorCodeBluetoothLENotAvailable = 1103,
    /**
     * 1104, Error caused when trying to redeem different region token.
     * It means not using the same region which was used during first time redemption
     */
    OrigoKeysErrorCodeRegionIncorrect = 1104,
    
    /**
     * 12234 OrigoKeysManager were unable to handle tokens that belongs to different environments. User either need to reinstall or clear app data before redeeming
     */
    OrigoKeysEnvironmentMisMatchError = 12234,
    /**
     * 12235 OrigoKeysManager doesn't support multiple HID Identity Positioning services for now. User either need to reinstall or clear app data before redeeming
     */
    OrigoKeysMultipleLocationServicesNotSupported = 12235,
    /**
     * 12235 HID Identity Positioning Sub Type Not Supported. Please check all pod dependencies, specifically make sure "OrigoNAOSDK" is added for OIP
     */
    OrigoKeysIdentityPositioningSubTypeNotSupported = 12236,
    /**
     * 15902  OrigoKeysManager were unable to serve the request since the requested application name is not registered. Recommended user action is to register their applicatiom name with US.
     */
    OrigoKeysApplicationNameNotAvailable = 15902,
    /**
     * 1601 This error code will be thrown when the user try to add the already added favorite reader.
     */
    OrigoKeysErrorCodeReaderAlreadyAddedAsFavorite = 1601,
    /**
     * 1602 This error code will be thrown when there are no favorite reader(s) available.
     */
    OrigoKeysErrorCodeNoFavoriteReadersAvailable = 1602,
    /**
     * 20220 This error occured when the entitlement isn’t present, Secure Element pass activation requires a special entitlement that Apple provides.
     * This error will also occurs, running on simulator and lower version of iOS 14.0 below.
     */
    OrigoKeysErrorCodeSecureElementNotavailable = 20220,
    /**
     * 20222 This error occured when there is invalid shareable meta data.
     */
    OrigoKeysErrorCodeSecureElementPassFailed = 20222,
    /**
     * 15920, The system canceled adding the pass due to an unknown failure.
     */
    OrigoKeysErrorCodeSecureElementUnknownError = 15920,
    /**
     * 15921, The user canceled adding the pass.
     */
    OrigoKeysErrorCodeSecureElementUserCanceledError = 15921,
    /**
     * 15922, Provisioning for secure element passes isn’t available on the device, or the app is missing the entitlement.
     */
    OrigoKeysErrorCodeSecureElementUnavailableError = 15922,
    /**
     * 15923, The configuration for the pass is invalid for either Wallet or the reader.
     */
    OrigoKeysErrorCodeSecureElementInvalidConfigurationError = 15923,
    /**
     * 15924, The reader for the pass isn’t supported or has an invalid version.
     */
    OrigoKeysErrorCodeSecureElementDeviceNotSupportedError = 15924,
    /**
     * 15925, The reader for the pass isn’t ready to start pairing.
     */
    OrigoKeysErrorCodeSecureElementDeviceNotReadyError = 15925,
    /**
     * 15926, The mobile operating system is not supported
     */
    OrigoKeysErrorCodesecureElementOSVersionNotSupportedError = 15926,
    /**
     * 15903, Unknown error.
     */
    OrigoKeysErrorCodePassKitUnknownError = 15903,
    /**
     * 15904, Invalid pass data..
     */
    OrigoKeysErrorCodePassKitInvalidDataError = 15904,
    /**
     * 15905, Unsupported pass version.
     */
    OrigoKeysErrorCodePassKitUnsupportedVersionError = 15905,
    /**
     * 15906, Invalid pass signature.
     */
    OrigoKeysErrorCodePassKitInvalidSignature = 15906,
    /**
     * 15907, Error caused by absence of the required entitlements for the given operation.
     */
    OrigoKeysErrorCodePassKitNotEntitledError = 15907,

    /**
     * 20232, Error caused due to Access token not found
     */
    OrigoKeysErrorCodeSSOAccessTokenNotFound = 20232,

    /**
     * 23110: The Origo server reported that service opted is not available in the Access token
     * Recommended action: Contact administrator.
     */

    OrigoKeysErrorCodeUnSupportedService = 23110,
    /**
     * 23111: The Origo server reported that issuance token is expired
     */

    OrigoKeysErrorCodeIssuanceTokenExpired= 23111



};
