// MobileKeysErrorCodes.h
// Copyright (c) 2014 ASSA ABLOY Mobile Services ( http://assaabloy.com/seos )
//
// All rights reserved.

#import <Foundation/Foundation.h>

/**
* The domain used for all NSError objects originating from Mobile Keys.
*/
extern NSErrorDomain MobileKeysErrorDomain;
/**
 * The domain used for all NSError objects originating from Mobile Keys while communicating with TSM.
 */
extern NSErrorDomain MobileKeysHttpErrorDomain;

/**
 *
 * NSError objects generated by MobileKeys will contain one of these codes.
 * Please look at the individual codes to see what they mean. The codes ending
 * in RetryError indicates that a retry can be attempted.
 *
 * @note since version 2.0
 */
typedef NS_ENUM(NSInteger, MobileKeysErrorCode) {
            /**
            * 99, An internal error occured. Recommended user action is to restart app or reboot device
            */
            MobileKeysErrorCodeInternal = 99,
            /**
            * 999, A fatal error occured. The keys have been lost and the user needs to setup again
            */
            MobileKeysErrorCodeCorruptedStorage = 999,
            /**
             * 107 Attempt to invoke a method which requires an endpoint that is setup. Recommended user action is to contact the key administrator and request an invitation code.
             */
            MobileKeysErrorCodeEndpointNotSetup = 107,
            /**
            * 401, One asynchrounous method of the API is already running. Recommended user action is to retry the action.
            */
            MobileKeysErrorCodeSDKBusy = 401,
            /**
            * 700, The TSM replied NOT ELIGIBLE (FATAL during Setup, Invitation code is consumed and can no longer be used). Recommended user action is to contact the key administrator.
            */
            MobileKeysErrorCodeDeviceNotEligible = 700,
            /**
            * 701, Server replied API INCOMPATIBLE. Recommended user action is to upgrade the application. Recommended developer is to upgrade the SDK.
            */
            MobileKeysErrorCodeSDKIncompatible = 701,
            /**
            * 702, The server communication failed. This is normally because of a network problem. Recommended user action is to check internet connectivity or try again later.
            */
            MobileKeysErrorCodeServerUnreachable = 702,
            /**
            * 703, The TSM failed to install the endpoint with a fatal error (FATAL, Invitation code no longer useful). Recommended user action is to contact the key administrator.
            */
            MobileKeysErrorCodeDeviceSetupFailed = 703,
            /**
             * 901 The TSM Reported that the invitation code was not valid. Recommended user action is to retype or contact the key administrator.
            */
            MobileKeysErrorCodeInvalidInvitationCode = 901,
            /**
            * 1101   MobileKeysManager was unable to serve the request to open the specified reader since the request contained
            *        an OpeningType that was not in the list of permitted OpeningTypes. Recommended user/developer action is to reconfigure reader.
            */
            MobileKeysErrorCodeOpeningTypeNotPermitted = 1101,
            /**
            * 1103  MobileKeysManager were unable to serve the request since Bluetooth Low Energy is unavailable. Recommended user action is to change permissions.
            */
            MobileKeysErrorCodeBluetoothLENotAvailable = 1103,
    /**
     * 1104 MobileKeysMananger was unable to resolve the region of TSM. Recommended developer action is to provide correct region code.
     */
    MobileKeysErrorCodeRegionIncorrect = 1104,
};
